# -*- coding: utf-8 -*-
"""project_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXVYMAhBTBfqEfroA5mq5OH4C-qMWn6J
"""

# =======================
# INSTALL + SETUP
# =======================
!pip install torch tqdm

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from copy import deepcopy

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =======================
# DOWNLOAD DATASET
# =======================
!wget https://files.grouplens.org/datasets/movielens/ml-100k.zip
!unzip ml-100k.zip

data_path = 'ml-100k/'

# =======================
# LOAD DATA
# =======================
id_val = 1
num_users = 943
num_items = 1682

train_dataframe = pd.read_csv(f'{data_path}u{id_val}.base', sep='\t', header=None)
train_dataframe.columns = ['user_id','item_id','rating','ts']
train_dataframe['user_id'] -= 1
train_dataframe['item_id'] -= 1

valid_df = pd.read_csv(f'{data_path}u{id_val}.test', sep='\t', header=None)
valid_df.columns = ['user_id','item_id','rating','ts']
valid_df['user_id'] -= 1
valid_df['item_id'] -= 1

# =======================
# DATASET CLASS
# =======================
class CollabDataset(Dataset):
    def __init__(self, df):
        self.user_tensor = torch.tensor(df['user_id'].values, dtype=torch.long)
        self.item_tensor = torch.tensor(df['item_id'].values, dtype=torch.long)
        self.target_tensor = torch.tensor(df['rating'].values, dtype=torch.float32)

    def __getitem__(self, index):
        return (self.user_tensor[index],
                self.item_tensor[index],
                self.target_tensor[index])

    def __len__(self):
        return len(self.user_tensor)

batch_size = 2000

train_dataset = CollabDataset(train_dataframe)
valid_dataset = CollabDataset(valid_df)

train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0)
valid_dataloader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=True, num_workers=0)

# =======================
# MODEL
# =======================
class ConcatNet(nn.Module):
    def __init__(self, config):
        super().__init__()

        self.emb_user = nn.Embedding(config['num_users'], config['emb_size'])
        self.emb_item = nn.Embedding(config['num_items'], config['emb_size'])

        self.fc = nn.Sequential(
            nn.Linear(config['emb_size']*2, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU()
        )

        self.head = nn.Linear(256, 1)
        self.out_range = config['out_range']

    def forward(self, user, item):
        u = self.emb_user(user)
        i = self.emb_item(item)
        x = torch.cat([u, i], dim=1)
        x = self.fc(x)
        x = torch.sigmoid(self.head(x))
        return x * (self.out_range[1]-self.out_range[0]) + self.out_range[0]

config = {
    'num_users': 943,
    'num_items': 1682,
    'emb_size': 50,
    'out_range': [0.8, 5.2]
}

model = ConcatNet(config).to(device)

# =======================
# TRAINING SETUP
# =======================
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=1
)

num_epoch = 10
early_stopping = 5

train_losses = []
valid_losses = []

best_loss = np.inf
no_improvements = 0

# =======================
# TRAIN LOOP
# =======================
for e in tqdm(range(num_epoch)):
    model.train()
    train_loss = 0

    for u,i,r in train_dataloader:
        u, i, r = u.to(device), i.to(device), r.to(device)
        r = r.unsqueeze(1)

        pred = model(u,i)
        loss = criterion(pred, r)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    train_loss /= len(train_dataset)
    train_losses.append(train_loss)

    model.eval()
    valid_loss = 0

    with torch.no_grad():
        for u,i,r in valid_dataloader:
            u, i, r = u.to(device), i.to(device), r.to(device)
            r = r.unsqueeze(1)

            pred = model(u,i)
            loss = criterion(pred, r)
            valid_loss += loss.item()

    valid_loss /= len(valid_dataset)
    valid_losses.append(valid_loss)

    print(f"Epoch {e}: Train Loss = {train_loss:.4f}, Valid Loss = {valid_loss:.4f}")

    scheduler.step(valid_loss)

    if valid_loss < best_loss:
        best_loss = valid_loss
        best_weights = deepcopy(model.state_dict())
        no_improvements = 0
    else:
        no_improvements += 1

    if no_improvements >= early_stopping:
        print("Early stopping triggered")
        break

# =======================
# PLOT
# =======================
plt.plot(train_losses, label="Train")
plt.plot(valid_losses, label="Valid")
plt.legend()
plt.show()